[config]
default_to_workspace = false

[tasks.backend]
description = "Run the backend server"
command = "cargo"
args = ["run", "-p", "backend"]

[tasks.build-backend]
description = "Run the backend server"
command = "cargo"
args = ["build", "--release", "-p", "backend"]

[tasks.frontend]
description = "Run the frontend development server"
dependencies = ["generate-schema"]
command = "npm"
args = ["run", "dev", "--prefix", "frontend"]

[tasks.build-frontend]
description = "Run the frontend development server"
dependencies = ["generate-schema"]
command = "npm"
args = ["run", "build", "--prefix", "frontend"]

[tasks.migration]
description = "Add a new database migration"
command = "sqlx"
args = ["migrate", "add", "-t", "-r", "${@}"]
cwd = "backend"

[tasks.undo-migration]
description = "Revert the last database migration"
command = "sqlx"
args = ["migrate", "revert"]
cwd = "backend"

[tasks.migrate]
description = "Run database migrations"
command = "sqlx"
args = ["migrate", "run"]
cwd = "backend"

[tasks.download-schema]
description = "Saves the OpenApi schema from the backend"
command = "cargo"
args = ["run", "-p", "backend", "--bin", "openapi_gen"]

[tasks.generate-schema]
description = "Generate the frontend API schema"
dependencies = ["download-schema"]
command = "npm"
args = ["run", "generate:api", "--prefix", "frontend"]


[tasks.dev]
description = "Run backend and frontend concurrently"
run_task = { name = ["backend", "frontend"], parallel = true }

[tasks.build]
dependencies = ["build-backend", "build-frontend"]
