-- Add down migration script here
ALTER TABLE users
ALTER COLUMN id TYPE INTEGER USING id::INTEGER;
ALTER TABLE users
ALTER COLUMN id DROP IDENTITY;

ALTER TABLE auth_sessions
ALTER COLUMN id TYPE INTEGER USING id::INTEGER;
ALTER TABLE auth_sessions
ALTER COLUMN id DROP IDENTITY;

ALTER TABLE variables
ALTER COLUMN id TYPE INTEGER USING id::INTEGER;
ALTER TABLE variables
ALTER COLUMN id DROP IDENTITY;

ALTER TABLE servers
ALTER COLUMN id TYPE INTEGER USING id::INTEGER;
ALTER TABLE servers
ALTER COLUMN id DROP IDENTITY;

ALTER TABLE ssh_keys
ALTER COLUMN id TYPE INTEGER USING id::INTEGER;
ALTER TABLE ssh_keys
ALTER COLUMN id DROP IDENTITY;

ALTER TABLE job_events
ALTER COLUMN id TYPE INTEGER USING id::INTEGER;
ALTER TABLE job_events
ALTER COLUMN id DROP IDENTITY;
