-- Add up migration script here
ALTER TABLE users
ALTER COLUMN id TYPE BIGINT USING id::BIGINT;
ALTER TABLE users
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE auth_sessions
ALTER COLUMN id TYPE BIGINT USING id::BIGINT;
ALTER TABLE auth_sessions
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE variables
ALTER COLUMN id TYPE BIGINT USING id::BIGINT;
ALTER TABLE variables
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE servers
ALTER COLUMN id TYPE BIGINT USING id::BIGINT;
ALTER TABLE servers
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE ssh_keys
ALTER COLUMN id TYPE BIGINT USING id::BIGINT;
ALTER TABLE ssh_keys
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE job_events
ALTER COLUMN id TYPE BIGINT USING id::BIGINT;
ALTER TABLE job_events
ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
